### ISSUE TITLE
Some endnotes are misnumbered

### ISSUE THREAD

**Issue by acabal** [standardebooks/leo-tolstoy_the-kingdom-of-god-is-within-you_leo-wiener#1]
@davgross Tracking issue for misnumbered endnotes. 

Example: note 14 is in chapter 4, but note 15 is in chapter 3.

All notes should be examined to ensure they are in the correct order, otherwise reading systems get super screwed up (that's how I noticed).

**Comment by davgross** [comment]
Hmmm... Goes to show. I went over that book I don't know how many times; not sure how that slipped through.
